### ISSUE TITLE
Mandar actualización de Bono Referente y Gasto internet?

### ISSUE THREAD

**Issue by brosenburt** [InteligenciaAnalitica/DIRECTORIO#281]
20 % $ 7.200

**Comment by brosenburt** [comment]
@iajuan  me ayudas a ver en que quedo este tema del Bono, ya pasamos la nueva regla?

**Comment by iajuan** [comment]
@brosenburt  bren, sobre este tema falta comunicar la nueva regla, habiamos quedado en que lo van a cobrar todos los que tengan cargada al menos 1 hora en un proyecto interno de IA, que serian:
REF
REDES 
SOPORTE
RRHH (ADS carga aca las hs de ingreso...esta ok o creariamos un proyecto INGRESO?)
