### ISSUE TITLE
Rol Gerente de Proyecto

### ISSUE THREAD

**Issue by iajuan** [InteligenciaAnalitica/DIRECTORIO#330]
Listar tareas que tendria
Como visibilizar el rol - Los referentes deberian verlo

**Comment by brosenburt** [comment]
@iajuan @PabloGottig 
Agrego el tema de delinear mas los roles, formalizándolos internamente y asignando tiempo mensual, ej: 
 - El de Abi en RRHH
 - El del rasti como Soporte IT

**Comment by iajuan** [comment]
@PabloGottig  @brosenburt 
Chicos, dejo un cuadro que arme para empezar a delinear las responsabilidades de cada rol. Deberia ser una buena base para que lo retoquemos y tengamos algo concreto.

![image.png](https://images.zenhubusercontent.com/5beed7130eedfd6716563b47/332b2879-c622-41ff-af91-6861d15e5129)
