### ISSUE TITLE
Asignaciones

### ISSUE THREAD

**Issue by brosenburt** [InteligenciaAnalitica/DIRECTORIO#5]
![image.png](https://images.zenhubusercontent.com/5d641b9cf9d8403f96fad9c2/4d52cbb5-80d6-49c6-af22-3c5065a88585)

**Comment by iajuan** [comment]
[https://app.zenhub.com/files/341253460/de63d938-9fce-4602-afe0-ce8e75792411/download](https://app.zenhub.com/files/341253460/de63d938-9fce-4602-afe0-ce8e75792411/download)

**Comment by brosenburt** [comment]
[https://app.zenhub.com/files/341253460/de20d53b-5601-46e0-b08b-646748d2efd4/download](https://app.zenhub.com/files/341253460/de20d53b-5601-46e0-b08b-646748d2efd4/download)

**Comment by brosenburt** [comment]
- **LBO** hace la capacitación de DW junto con LG y después hace Tabular para evaluar posible asignación a Tenaris
- **SM** esperar la oferta a ver como se desenvuelve LBO en Tabular, que lo contacte Sabrina para dilatar 
- **BM** esperar a ver si tomamos a SM para que hagan las capacitaciones en conjunto

**Comment by brosenburt** [comment]
**7/4** Lucas Guerrini -> Milicic
**12/4** Leonel Bordon -> Tenaris
